# Generated by Django 5.0.7 on 2024-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="student", managers=[],),
        migrations.AlterModelManagers(name="teacher", managers=[],),
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
