# Generated by Django 5.0.7 on 2024-07-14 06:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_student_managers_alter_teacher_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="teacher",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
