# Generated by Django 5.0.7 on 2024-07-16 09:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_student_managers_alter_teacher_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="teacher",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
